name: GoonClansEngine
version: 0.9.1-PreRelease
main: com.yourdomain.goonclansengine.GoonClansEngine
api-version: 1.21.4
commands:
  clan:
    description: Simple ClansEngine Created Specially for SMP by Ketsman_Show
    usage: /clan <create | invite | join | accept | kick | leave | disband | transfer>
  clans:
    description: List all clans.
    usage: /clans [help]
  dar:
    description: Grant permission to create a clan.
    usage: /dar <player>